config/routes.rb
Meetingsapp::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :rooms do
    resources :messages
    resources :invitations
  end

  resources :authentications, :only => [:index, :create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => 'rooms#index'

  mount Resque::Server, :at => "/resque"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :room
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
end

app/controllers/messages_controller.rb
class MessagesController < BaseRoomController
  respond_to :html, :json
  before_filter :authenticate_user!

  expose(:room) {
    Room.fetch params[:room_id]
  }
  expose(:messages) { room.messages.includes(:author) }
  expose(:message)

  def index
    respond_with messages
  end

  def show
    respond_with message
  end

  def new
    respond_with message
  end

  def edit
    respond_with message
  end

  def create
    if message.save
      flash.notice = 'Message was created successfully.'
    end
    respond_with message
  end

  def update
    if message.save
      flash.notice = 'Message was updated successfully.'
    end
    respond_with message
  end

  def destroy
    message.destroy
    respond_with message
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for([room, message]) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.association :room %>
    <%= f.association :author %>
    <%= f.input :type %>
    <%= f.input :content %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<table id="messages" class="zebra-striped">
  <tbody>
    <%- messages.each do |message| %>
      <tr class="message">
        <td class="user"><%= message.author %></td>
        <td><%= message.content %></td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', room_messages_path(room) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Room:</b>
  <%= message.room %>
</p>

<p>
  <b>Author:</b>
  <%= message.author %>
</p>

<p>
  <b>Type:</b>
  <%= message.type %>
</p>

<p>
  <b>Content:</b>
  <%= message.content %>
</p>


<%= link_to 'Edit', edit_message_path(message) %> |
<%= link_to 'Back', messages_path %>