config/routes.rb
Meetingsapp::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :rooms do
    resources :messages
    resources :invitations
  end

  resources :authentications, :only => [:index, :create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => 'rooms#index'

  mount Resque::Server, :at => "/resque"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  respond_to :html, :json

  expose(:authentications) { current_user.authentications }
  expose(:authentication)

  def index
    respond_with authentications
  end

  def create
    omniauth = request.env['omniauth.auth']
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])

    if authentication
      flash.notice = "Signed in successfully."
      cookies.signed[:auth_token] = authentication.user.auth_token
      redirect_to root_url
    elsif current_user
      current_user.authentications.create! provider: omniauth['provider'], uid: omniauth['uid']
      flash.notice = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash.notice = "Signed in successfully"
        cookies.signed[:auth_token] = user.auth_token
        redirect_to root_url
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to signup_url
      end
    end
  end

  def destroy
    authentication.destroy
    respond_with authentication
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= simple_form_for(authentication) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.association :user %>
    <%= f.input :provider %>
    <%= f.input :uid %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= link_to 'Destroy', authentication, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= authentication.user %>
</p>

<p>
  <b>Provider:</b>
  <%= authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(authentication) %> |
<%= link_to 'Back', authentications_path %>