config/routes.rb
Meetingsapp::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :rooms do
    resources :messages
    resources :invitations
  end

  resources :authentications, :only => [:index, :create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => 'rooms#index'

  mount Resque::Server, :at => "/resque"

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room

  before_create { self.token = SecureRandom.urlsafe_base64 }
end

app/controllers/invitations_controller.rb
class InvitationsController < BaseRoomController
  respond_to :html, :json

  before_filter :authenticate_user!, :except => [:accept]

  expose(:invitations) { room.invitations.page params[:page] }
  expose(:invitation)

  def index
    respond_with invitations
  end

  def new
    respond_with invitation
  end

  def create
    invitation.user = current_user
    if invitation.save
      flash.notice = 'Invitation was created successfully.'
    end
    respond_with invitation
  end

  def destroy
    invitation.destroy
    respond_with invitation
  end

  def accept
    invitation = Invitation.find_by_token params[:token]
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= simple_form_for([room, invitation]) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.association :user %>
    <%= f.association :room %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :status %>
    <%= f.input :token %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.name %></td>
    <td><%= invitation.email %></td>
    <td><%= invitation.status %></td>
    <td><%= link_to 'Destroy', [room, invitation], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Invitation', new_room_invitation_path(room) %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', room_invitations_path(room) %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= invitation.user %>
</p>

<p>
  <b>Room:</b>
  <%= invitation.room %>
</p>

<p>
  <b>Name:</b>
  <%= invitation.name %>
</p>

<p>
  <b>Email:</b>
  <%= invitation.email %>
</p>

<p>
  <b>Status:</b>
  <%= invitation.status %>
</p>

<p>
  <b>Token:</b>
  <%= invitation.token %>
</p>


<%= link_to 'Edit', edit_invitation_path(invitation) %> |
<%= link_to 'Back', invitations_path %>