config/routes.rb
Meetingsapp::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :rooms do
    resources :messages
    resources :invitations
  end

  resources :authentications, :only => [:index, :create, :destroy]
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => 'rooms#index'

  mount Resque::Server, :at => "/resque"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room

  before_create { self.token = SecureRandom.urlsafe_base64 }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :room
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
end

app/models/room.rb
class Room < ActiveRecord::Base
  extend ActiveSupport::Memoizable

  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"
  has_many :memberships, :dependent => :destroy
  has_many :admins, :through => :memberships, :class_name => "User", :source => :user,
                    :conditions => 'memberships.role = "admin"'
  has_many :members, :through => :memberships, :class_name => "User", :source => :user
  has_many :invitations, :dependent => :destroy
  has_many :messages, :dependent => :destroy

  validates_presence_of :name

  before_create { self.token = SecureRandom.urlsafe_base64(32) }
  after_save { Rails.cache.write("rooms/#{id}", self) }
  after_destroy { Rails.cache.delete("rooms/#{id}") }

  def self.fetch(id)
    Rails.cache.fetch("rooms/#{id}") { find(id) }
  end

  def join!(user)
    REDIS.zadd(redis_key(:online_users), Time.now.utc.to_f, user.id)
    @online_users = nil
  end

  def leave!(user)
    REDIS.zrem(redis_key(:online_users), user.id)
    @online_users = nil
  end

  def online_users_count
    REDIS.zcount(redis_key(:online_users), 0, Time.now.utc.to_f)
  end

  def online_users
    # TODO Query does not preserve the order in redis, so we need to order
    # the returned users row set.
    @online_users ||= begin
      user_ids = REDIS.zrangebyscore(redis_key(:online_users), 0, Time.now.utc.to_f)
      user_ids.present? ? User.where(:id => user_ids) : []
    end
  end

  def redis_key(prefix)
    "rooms/#{self.id}/#{prefix}"
  end

  def to_s
    name
  end

  memoize :redis_key
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  has_many :owned_rooms, :class_name => "Room", :foreign_key => "owner_id", :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :rooms, :through => :memberships
  has_many :invitations, :dependent => :destroy
  has_many :authentications, :dependent => :destroy

  before_create { generate_token(:auth_token) }

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def to_s
    name || email
  end

  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    self.name = omniauth['user_info']['name'] if name.blank?
    self.password = self.password_confirmation = SecureRandom.urlsafe_base64
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def self.fetch_by_auth_token(auth_token)
    Rails.cache.fetch "users/token/#{auth_token}" do
      find_by_auth_token(auth_token)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  layout :application_layout

  def current_user
    @current_user ||= User.fetch_by_auth_token(cookies.signed[:auth_token]) if cookies[:auth_token]
  end

  def authenticate_user!
    redirect_to login_url unless current_user
  end

  def application_layout
    current_user ? 'application' : 'site'
  end
end

app/controllers/base_room_controller.rb
class BaseRoomController < ApplicationController
  before_filter :authenticate_user!

  expose(:rooms) { current_user.rooms }
  expose(:room)

  layout :set_layout

  def set_layout
    request.headers['X-PJAX'].present? ? false : 'room'
  end
end

app/controllers/messages_controller.rb
class MessagesController < BaseRoomController
  respond_to :html, :json
  before_filter :authenticate_user!

  expose(:room) {
    Room.fetch params[:room_id]
  }
  expose(:messages) { room.messages.includes(:author) }
  expose(:message)

  def index
    respond_with messages
  end

  def show
    respond_with message
  end

  def new
    respond_with message
  end

  def edit
    respond_with message
  end

  def create
    if message.save
      flash.notice = 'Message was created successfully.'
    end
    respond_with message
  end

  def update
    if message.save
      flash.notice = 'Message was updated successfully.'
    end
    respond_with message
  end

  def destroy
    message.destroy
    respond_with message
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_user!

  expose(:rooms) { current_user.rooms.page params[:page] }
  expose(:room)

  def index
    respond_with rooms
  end

  def show
    respond_with room
  end

  def new
    respond_with room
  end

  def edit
    respond_with room
  end

  def create
    room.owner = current_user
    if room.save
      room.memberships.create! user: current_user, role: :admin
      flash.notice = 'Room was created successfully.'
    end
    respond_with room
  end

  def update
    if room.save
      flash.notice = 'Room was updated successfully.'
    end
    respond_with room
  end

  def destroy
    room.destroy
    respond_with room
  end

  layout :set_layout

  def set_layout
    request.headers['X-PJAX'].present? ? false : 'application'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.signed.permanent[:auth_token] = user.auth_token
      else
        cookies.signed[:auth_token] = user.auth_token
      end
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    cookies.delete :auth_token
    redirect_to root_url, :notice => "Logged out successfully."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose :user

  def new
  end

  def create
    if user.save
      cookies.signed.permanent[:auth_token] = user.auth_token
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>meetings</title>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans" %>
  <%= stylesheet_link_tag "application" %>
  <%= tag :meta, name: "google-site-verification", content: "pIVsLi9FQg1ET9O2MHcrIsL56uf1NfhppBlE-YSF2PQ" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<div class="topbar-wrapper" style="z-index: 5;">
  <div class="topbar">
    <div class="topbar-inner">
      <div class="container">
        <h3><%= link_to "meetings", rooms_path %></h3>
        <form action="">
          <input type="text" placeholder="Search" id="q">
        </form>
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle">Rooms</a>
            <ul class="dropdown-menu">
              <%- current_user.rooms.each do |room| %>
                <li>
                  <%= link_to room.name, room %>
                </li>
              <% end -%>
            </ul>
          </li>
          <li><%= link_to "+ New Room", new_room_path %></li>
        </ul>
        <ul class="nav secondary-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"><%= current_user %></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Log out", logout_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<% if content_for? :content %>
  <%= yield :content %>
<% else %>
  <div class="container">
    <div class="content">
      <%= yield %>
    </div>
  </div>
<% end -%>

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js" %>
<%= javascript_include_tag "//cdn.pubnub.com/pubnub-3.1.min.js" %>
<%= javascript_include_tag "application" %>

<script>
window._gaq = window._gaq || [];
_gaq.push(['_setAccount', 'UA-25788038-1']);
_gaq.push(['_trackPageview']);
(function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</body>
</html>

app/views/layouts/room.html.erb
<%= content_for :content do %>
<div class="heading container-fluid">
  <h2><%= room %> <small id="topic"><%= room.topic %></small></h2>
</div>

<div class="container-fluid">
  <div class="sidebar">
    <ul class="unstyled" id="room-menu">
      <li><%= link_to "Messages", room_messages_path(room), class: 'messages' %></li>
      <li><a href="{{ reverse_url('files', room._id) }}" class="files">Files</a></li>
      <li><a href="{{ reverse_url('transcripts', room._id) }}" class="transcripts">Transcripts</a></li>
        <li><a href="{{ reverse_url('members', room._id) }}" class="members">Members</a></li>
        <li><%= link_to "Invitations", room_invitations_path(room), class: 'invitations' %></li>
        <li><%= link_to "Settings", edit_room_path(room), class: "settings" %></li>
      <li><a href="{{ reverse_url('leave_room', room._id) }}" class="leave">Leave</a></li>
    </ul>
    <h4>Who's here?</h4>
    <ul class="unstyled" id="room-users">
      <% room.online_users.each do |user| %>
        <%= content_tag_for :li, user do %><%= user %><% end -%>
      <% end -%>
    </ul>
  </div>
  <div class="content" id="content">
    <%= yield %>
  </div>
</div>

<div id="footer">
  <div id="footer-content" class="container-fluid">
    <div class="sidebar">
    </div>
    <div class="content">
      <div class="row">
        <div class="span12">
          <form action="{{ reverse_url('new_message', room._id) }}" method="post" id="new_message">
            <textarea id="text_content" name="content"
                      placeholder="Type your message or drop your files here and hit enter..."></textarea>
          </form>
        </div>
        <div class="span2">
          <div id="upload_container">
            <!--<div id="filedrop" style="border:1px solid red; padding:10px">
              Drop files here
            </div>-->
            <div id="filelist"></div>
            <div id="upload_buttons" style="display:none">
              <a href="#" id="select_files" class="btn" style="display:none">Select files</a>
              <a href="#" id="upload" class="btn primary">Upload files</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <audio id="snd_new" src="/static/sounds/New.mp3"></audio>
<audio id="snd_off" src="/static/sounds/Off.mp3"></audio>
<audio id="snd_on" src="/static/sounds/On.mp3"></audio> -->
<% end -%>
<%= render :template => 'layouts/application' %>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>meetings</title>
  <%= stylesheet_link_tag(
    "http://twitter.github.com/bootstrap/assets/css/bootstrap-1.2.0.min.css",
    "http://fonts.googleapis.com/css?family=Open+Sans",
    "application"
    ) %>

  <script>
  window._gaq = window._gaq || [];
  _gaq.push(['_setAccount', 'UA-25788038-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>

  <meta name="google-site-verification" content="pIVsLi9FQg1ET9O2MHcrIsL56uf1NfhppBlE-YSF2PQ" />
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
  <%= yield %>
  <%= javascript_include_tag(
    "//ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js",
    "application"
  ) %>
  <%= javascript_include_tag "http://cdn.pubnub.com/pubnub-3.1.min.js" %>
</body>
</html>